version: '3.2'

services:

  nodemanager:
    build:
      context: manager/app
      args:
        GRADLE_VERSION: "4.10.3"
        APP_PORT: 9100
    image: nodemanager
    container_name: nodemanager
    ports:
      - 9100:9100
      - 9090:9090
    networks:
      - mongodb
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 12000M

  mongodb:
    image: mongo
    container_name: mongo-db-container
    expose:
      - 27017
    networks:
      - mongodb
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4000M

networks:
  mongodb:
    driver: bridge