version: '2.3'

volumes:
  nodemanager-volume:
  mongodb-volume:

services:

  nodemanager:
    build:
      context: app
      args:
        GRADLE_VERSION: "4.10.3"
        APP_PORT: 9100
    image: nodemanager
    container_name: nodemanager
    volumes:
      - nodemanager-volume:/root
    ports:
      - 9100:9100
      - 9090:9090
    networks:
      - mongodb
    mem_limit: 12000m

  mongodb:
    image: mongo
    container_name: mongo-db-container
    volumes:
      - mongodb-volume:/data/db
    expose:
      - 27017
    networks:
      - mongodb
    mem_limit: 4000m

networks:
  mongodb:
    driver: bridge